### PR TITLE
adds Arquillian-Pact announcement

### PR DESCRIPTION
**Pull request by lordofthejars**
This change is [Reviewable](https://reviewable.io/reviews/arquillian/arquillian.github.com/349)

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Hmm when you merge your own PR there is little to no sense with opening it :)

**Comment by lordofthejars** [comment]
it was reviewed by Matous :)

**Comment by bartoszmajsak** [comment]
No trace here :)

**Comment by lordofthejars** [comment]
I know, we talked in hipchat

**Pull request merged**
