### PR TITLE
Update Forge commands in getting started guide (all languages)

### PR DESCRIPTION
**Pull request by oscerd**
Update Forge command in all languages getting started guides.

Andrea

### CODE REVIEW

**Comment by aslakknutsen** [comment]
Excellent! Missing one tho, the English guide :)

https://github.com/arquillian/arquillian.github.com/blob/develop/guides/getting_started.textile

You mind updating that as well?

**Comment by oscerd** [comment]
Hi Aslak,

Yes :-) I'll do this change, rebase and push :-)

**Comment by oscerd** [comment]
Rebased and pushed again :-)

**Comment by aslakknutsen** [comment]
Thank you! :)

**Pull request merged**
