### PR TITLE
Fixed CDI API version mismatch by updating Java EE 6 to Java EE 7

### PR DESCRIPTION
**Pull request by dipak-pawar**
Fixed conflicts for weld. Weld required version CDI 1.1 or better. CDI 1.0 API detected due to Java EE6

---
This change is [Reviewable](https://reviewable.io/reviews/arquillian/arquillian.github.com/337)

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Thanks for the contribution @dipak-pawar! Can you also adjust guides in other languages?

  * `getting_started_de.textile`
  * `getting_started_el_gr.textile`
  * `getting_started_es.textile`	
  * `getting_started_fr.textile`
  * `getting_started_it.textile`
  * `getting_started_ja.textile`
  * `getting_started_nl.textile`
  * `getting_started_pl.textile`
  * `getting_started_pt.textile`

**Comment by dipak-pawar** [comment]
@bartoszmajsak  Adjusted guides in other languages as well.

**Comment by bartoszmajsak** [comment]
There are few other minor things which would be great to bring together with this PR.

Forge commands, such as

```
project-add-dependencies org.jboss.spec:jboss-javaee-6.0:1.0.0.Final:provided:pom
````
still points to the wrong version. Sample generated POM which we paste as the one Forge generated should be adjusted accordingly. 

Also, the warning about Java EE 6 API should be entirely removed, as we are not using `7.0` version, which I believe doesn't have this problem anymore. Exactly this section:

> The org.jboss.spec:jboss-javaee-6.0 artifact is comprised of only standard Java EE 6 APIs. We strongly recommend that you do not use the Java EE API artifact with coordinates javax:javaee-api. The latter artifact contains classes with stripped method bodies, which will cause your application to throw obscure Absent Code errors if present on the classpath at runtime (even when running tests). Read this FAQ for more details.

In addition, we could bump JUnit version from `4.8.2` to latest `4.12`.

**Comment by dipak-pawar** [comment]
@bartoszmajsak Updated PR with all suggested changes. Please have a look into it.

**Comment by bartoszmajsak** [comment]
Great! Thanks a lot!

**Comment by bartoszmajsak** [comment]
Upstream @2c9c3a8. Thanks!

**Pull request closed without merging**
