### PR TITLE
added german translation of testing java persistence guide

### PR DESCRIPTION
**Pull request by bennetelli**

### CODE REVIEW

**Comment by bennetelli** [comment]
@aslakknutsen here's the german translation of testing java persistence guide.

**Comment by aslakknutsen** [comment]
woo! Thank you! 

@myfear You want to do a quick read through?

**Comment by myfear** [comment]
Looks good to me! Thank you!

**Comment by aslakknutsen** [comment]
Pushed upstream and live:
https://github.com/arquillian/arquillian.github.com/commit/370280b8cfb3c19370029e9f40bdb5011122f804

**Pull request closed without merging**
