### PR TITLE
fixed some typos in the german getting started guide

### PR DESCRIPTION
**Pull request by bennetelli**

### CODE REVIEW

**Comment by myfear** [comment]
Hey @aslakknutsen @bartoszmajsak can any of you merge this please? Thanks!

**Comment by aslakknutsen** [comment]
Thank you! :)

**Comment by bennetelli** [comment]
You're welcome :) will translate the other missing guides into german the next days, too.

**Comment by aslakknutsen** [comment]
oh, most excellent! :+1:

**Pull request closed without merging**
