### PR TITLE
Fixes java-ee version with forge project

### PR DESCRIPTION
**Pull request by tobiashochguertel**
#### Short description of what this resolves:

Fixes the Issue which is described in #366.

#### Changes proposed in this pull request:

- changed version number in project creating with forge.

**Fixes**: #

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Thank you for your contribution!

**Comment by tobiashochguertel** [comment]
Thank you :)

**Comment by tobiashochguertel** [comment]
@bartoszmajsak I miss the fixed version of the documentation on the arquillian website. Is thought this would happen immediately?

**Comment by bartoszmajsak** [comment]
It would if the build process wouldn't need some changes - I'm working on it. It's not a trivial textile to HTML generation. Stay tuned.

**Comment by tobiashochguertel** [comment]
Is there an github project with the build process and an issue which describes the needed changes where I can contribute?

**Comment by bartoszmajsak** [comment]
It's this exact project - issue is being fixed as we speak, but if you would be interested in helping us (which is more than awesome!) please have a look at [help-wanted](https://github.com/arquillian/arquillian.github.com/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) or  [improvement](https://github.com/arquillian/arquillian.github.com/issues?q=is%3Aissue+is%3Aopen+label%3Aimprovement) tags in this repo.

**Pull request merged**
