### PR TITLE
Update versions of Weld artifacts in getting_started document

### PR DESCRIPTION
**Pull request by tremes**
This change is [Reviewable](https://reviewable.io/reviews/arquillian/arquillian.github.com/320)

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Hey, thanks for the pull request. With those versions I assume all is still working?

**Comment by tremes** [comment]
I didn't try that but I am 90% sure that it is.:-) We use this Weld embedded container 1.0.0.CR9 in Weld and Weld 2.3.4.Final is the latest stable version.

**Comment by bartoszmajsak** [comment]
Before we can take it upstream we need one more improvement here

- [ ] Update other language versions of the guide

Would you have time to take care of it?

**Comment by tremes** [comment]
Closed in favor of https://github.com/arquillian/arquillian.github.com/pull/326

**Pull request closed without merging**
